### ISSUE TITLE
Attempting to generate trees causes text to disappear

### ISSUE THREAD

**Issue by kmanwar89** [ramtinsoltani/atom-ascii-tree#1]
I'm using this package on Windows 10, running Atom 1.36.0 x64.

Each time I attempt to run the package using either the shortcut, or from the Atom command menu, the text I highlight disappears.

This does not happen if I create a new document -- I can get the tree structure to generate exactly once; any subsequent attempts do not work.

I'm not sure if you are actively developing this plugin still or not, but I'd appreciate any help. I haven't found another plugin with the same behavior that I could use instead.

**Comment by ramtinsoltani** [comment]
@kmanwar89 I can't reproduce the bug using Atom 1.37.0 x64 Windows 10. Are you highlighting the whole document text or just the input tree?

Can you provide your input or something similar which reproduces the problem?

**Comment by kmanwar89** [comment]
I've tried both ways - highlighting all text, or highlighting just the tree -- same result.  I actually (unintentionally) created another issue under Issue #2 when prompted by Atom -- after upgrading, it won't even run the plugin at all, and Atom prompts to create the issue on Github. That also contains the dump of the error log that might be helpful?

**Comment by ramtinsoltani** [comment]
@kmanwar89 So there's currently a bug where the child nodes disappear when your root node has indentation. Is that what's causing the bug on your end? If not, pasting the exact tree in your input would help me investigate the problem.

For the plugin not running, I've just updated Atom and everything's fine on my end. Try reinstalling the plugin and see if it works.
