### ISSUE TITLE
Generate removes all content except first and last lines

### ISSUE THREAD

**Issue by dantechguy** [ramtinsoltani/atom-ascii-tree#4]
A quick example, using the demo listed on this repo:
![image](https://user-images.githubusercontent.com/30006489/93259966-95e31b80-f798-11ea-85b9-393fb514a7b2.png)
Then merely turns into this!
![image](https://user-images.githubusercontent.com/30006489/93260003-a2677400-f798-11ea-893c-ec68eace81b2.png)
Pretty weird, and would be handy if it was fixed!

**Comment by ramtinsoltani** [comment]
Hey @dantechguy 

I can't replicate that issue, can you please provide your Atom and ascii-tree package version?

This is what I got using ascii-tree 1.2.0 and Atom 1.51.0 x64 (macos):

<img width="328" alt="Screen Shot 2020-09-24 at 12 40 58 AM" src="https://user-images.githubusercontent.com/7918069/94115764-0aeccb80-fdff-11ea-8b45-335e17d8d290.png">
<img width="329" alt="Screen Shot 2020-09-24 at 12 41 12 AM" src="https://user-images.githubusercontent.com/7918069/94115803-16d88d80-fdff-11ea-84ce-ecbe1d218c05.png">

**Comment by ghost** [comment]
Same problem for me. I took your own README example and got only root and file5

**Comment by ramtinsoltani** [comment]
@dimitridamasceno Can you please provide your Atom and ascii-tree package versions? I need to make sure you're using the latest version of the package since I can't replicate this issue.

The package had bugs before the rewrite in the previous version, and I changed the whole logic in the new release to avoid bugs like that.

**Comment by ramtinsoltani** [comment]
@dimitridamasceno @dantechguy I was able to replicate the problem on a Windows machine. Turns out it was a regular expression issue with Windows `\r\n` new line characters.

The new version (1.2.1) is released now and it should fix this issue.

Thank you both for reporting this bug.
